<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomerDirectory.Application\CustomerDirectory.Application.csproj" />
    <ProjectReference Include="..\CustomerDirectory.Infrastructure\CustomerDirectory.Infrastructure.csproj" />
  </ItemGroup>

</Project>
